import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
// import { Geist, Geist_Mono , Merienda , Montserrat} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import AppLinks from "@/components/applinks/appLinks";
import Footer from "@/components/footer";
import ReduxProvider from "@/redux/reduxProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// const merienda = Merienda({
//   weight: "400",
//   variable: "--font-merienda",
//   subsets: ["latin"],
// });

// const montserrat = Montserrat({
//   weight: "400",
//   variable: "--font-merienda",
//   subsets: ["latin"],
// });



export const metadata: Metadata = {
  title: "Pettro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable}
          antialiased bg-white` }
      >
        <ReduxProvider>
        <Navbar/>
        <AppLinks />
        {children}
        <Footer/>
        </ReduxProvider>
      </body>
    </html>
  );
}
